### PR TITLE
Update msgpack5

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Tested locally, all tests pass without changes

### CODE REVIEW

**Comment by tarruda** [comment]
Can you rebase? I have updated the travis script.

**Comment by SevereOverfl0w** [comment]
Done

**Comment by tarruda** [comment]
Ty

**Comment by SevereOverfl0w** [comment]
Are you able to go ahead and bump the dependent versions in all places it's used?

**Comment by tarruda** [comment]
Updated and published node-client. cc @nhynes for a node-host update

**Pull request merged**
